### ISSUE TITLE
WARNING: Unlicensed version of AIR SDK

### ISSUE THREAD

**Issue by nyuntaka** [Gamua/Adobe-Runtime-Support#377] opened 2020-07-04 01:32 UTC
Today, I used the latest version sdk(33.1.1.176). My app doesn't launch with the error message.
"WARNING: Unlicensed version of AIR SDK"
That has never happened before. I used the sdk version 33.1.1.50 until yesterday. I'm using free license.
P.S. I'm sorry my English is bad.
![Screenshot_2020-07-04-09-30-51](https://user-images.githubusercontent.com/14065274/86502746-7a938180-bde1-11ea-8a0a-51aab6c06c0c.png)

**Comment by ajwfrost** [comment] 2020-07-04 06:38
Can you send us your APK to check this please? And can you please confirm what device you're running it on?
thanks
https://transfer.harman.com/requests/Afuzgv17bFx0d1VSbZJHp5

**Comment by nyuntaka** [comment] 2020-07-05 08:47
Thank you. I sent the APK yesterday. Device: SH-06E Android 4.4.2

**Comment by ajwfrost** [comment] 2020-07-06 08:42
Hi
Looks like there were some files left in the SDK that should have been removed! Can you please try manually removing them:
```
[SDK folder]\lib\android\lib\resources\app_entry\res\drawable\splash_landscape.png
[SDK folder]\lib\android\lib\resources\app_entry\res\drawable\splash_portait.png
```
Apologies for that :-(
thanks
  Andrew

**Comment by nyuntaka** [comment] 2020-07-06 23:05
I deleted them and tried it. However, nothing changes. Same error.
Thank you.

**Comment by ajwfrost** [comment] 2020-07-08 08:25
@nyuntaka I'm assuming then that if you rebuild, and you examine the APK file in a zip manager, you don't see those files any more in the 'drawable' folder? Are you able to send us the new package and we can examine it .. will also look at a different way to validate these files..
https://transfer.harman.com/requests/LY3BzXf5DjNeZ6ey9FKBIQ

**Comment by nyuntaka** [comment] 2020-07-08 11:47
Yes, I don't see those files any more in the 'drawable' folder.
I send the new apk file.

**Comment by ajwfrost** [comment] 2020-07-09 06:43
@nyuntaka thanks - so it worked for me on a recent Android handset, let me dig out a 4.4 version and see if this is the difference..

**Comment by ajwfrost** [comment] 2020-07-09 11:04
@nyuntaka slightly odd - yes we can reproduce this issue on an older device but it's not clear why there's a difference here. 
We are updating this to change to a more foolproof process so this should be fixed shortly... Thanks for all the support in tracking down the issue!

**Comment by juvelez** [comment] 2020-07-13 18:24
Hi,

I have exactly the same error with exactly the same AIR version, I've tested and not working on:

Galaxy Note 3 - Android 5.0
Galaxy S10E - Android 9.0
Galaxy S5 - Android 6.0.1
Galaxy Tab A - Android 7.1.1
Asus Memo Pad HD 7 - Android 4.2.2

And tested and working on:

Galaxy S7 Edge - Android 8.0
Galaxy Tab S4 - Android 9.0
Motorola Moto G6 Plus - Android 9.0

The only files I've added were the Adaptive Icons, on:
d:\Dev\Adobe AIR SDK\Harman\33.1.1.176\lib\android\lib\resources\app_entry\res

It is mandatory due to restrictions of Google, they are asking to include the icons for the most recent versions of Android, and the only way to do that is adding those files directly to the Air SDK, if the icons are not added the apps could be removed from store some day. Harman must pay attention on the Launcher images replacement, but NOT THE ICONS, I hope that is not the reason.

**Comment by ajwfrost** [comment] 2020-07-14 10:30
Hi - are you able to get the latest version now (33.1.1.190) and confirm that this no longer is a problem?

thanks

**Comment by nyuntaka** [comment] 2020-07-14 13:18
I confirmed that this no longer is a problem. Thank you very much.

**Comment by ajwfrost** [comment] 2020-07-14 16:30
Great, thanks!

**Closed by ajwfrost** 2020-07-14 16:30 UTC
Labels: Bug, Platform: Android, Runtime: AIR

**Comment by juvelez** [comment] 2020-07-14 17:50
Confirmed too, I have updated 3 apps and all the tests on 9 different versions of Android were successful.

**Comment by ajwfrost** [comment] 2020-07-14 17:57
Thanks @juvelez!
