### ISSUE TITLE
Adobe Animate  & Harman AIR SDK video bug

### ISSUE THREAD

**Issue by micha01** [Gamua/Adobe-Runtime-Support#779] opened 2021-04-09 09:14 UTC
Since AIR SDK 32.0.0.116 there is a heavy bug  in AIR which makes it impossiple to produce new multimedia desktop applications with Adobe Animate or to change or to update older apps. Since AIR 32 you cannot play multiple videos in a row. 

My Windows 10 desktop apps produced with Animate 2021 and newest Harman’s AIR SDK 33.1.1.444 are stopping to play videos (state of art 1920 x 1080) exactly at the seventh attempt to start a new one. But same projects produced with Animate 2019 and AIR 31 are working fine. Attached are two screenshots of Adobe Scout. The Scout_AIR_31.JPG shows no memory problems even after dozens of player restarts with multiple videos. In Scout_AIR_33.JPG there is high memory consumption as soon as you start playing a video and a overflow after the seventh restart. This may be the reason for the crash.

It´s not a sole H.264 (mp4) issue. Same problem appears with flv files. Doesn’t matter using the Animate built in FLVPlayback class or the stagevideo object. 

This issue is aggravated by the fact that since Animate 2020 you can’t install AIR SDK lower than version 32. Even worse: in Adobe Creatice Cloud there is no way to install Animate versions older than version 20.

![Scout_AIR_31](https://user-images.githubusercontent.com/13662729/114157697-3612b480-9924-11eb-90bb-00ca9912f994.JPG)
![Scout_AIR_33](https://user-images.githubusercontent.com/13662729/114157702-36ab4b00-9924-11eb-994b-6da41af75a3e.JPG)

**Comment by ajwfrost** [comment] 2021-04-09 10:57
Hi - there were some changes in the AIR runtime in the later v32 updates due to a change in codec support which is behind these issues. Interesting that it's happening in FLV videos though as the changes shouldn't have affected the On2/Sorenson codecs. 

The above Scout screenshots don't seem to show the memory usage, those charts are the frame times?

We are looking into the memory consumption though, there are other issues reported regarding the clean-up of the NetStream object although in our test cases it's all working fine so there may be some complexities as to objects being held open and not cleaning up properly through the garbage collector.

We are intending to rework all the multimedia handling though which should eliminate these problems.

thanks

**Comment by micha01** [comment] 2021-04-10 08:52
Hi Andrew,

right: FLV videos with Sorenson codec are playing without the discribed problems. But who uses FLV & Sorenson yet? Adobe itself  turned off the FLV encoder in it’s Media Encoder.

And right: The NetStream object seems to cause the problems. Desktop builts made with Animate 2019 and AIR SDKs older than 32.0.0.89 are working fine. You can end StageVideo and cleanning up NetStream properly with this simple function:

function video_stop()
{
	if (StageVideo != null){	
		StageVideo.attachNetStream(null)
		NetStream.close();
	}
}

With this multiple videos can be ended and (re)started in an endless row. But same function fails with all AIR SDKs younger than 32.0.0.89. Even an additional „System.gc()“ forcing garbage collector to free memory doesn’t help.

Playing state of art videos (H.264, Full HD) is a fundamental task for all authors of multimedia apps. So please give as a note when the mentioned „rework“ will be done.

Best regards
Michael

**Comment by ajwfrost** [comment] 2021-04-12 11:14
Hi @micha01 

Thanks for this .. we've just been reviewing this code and running some more tests with advanced profiling tools, and have found a couple of issues in the initial implementation of the new Windows decoders. So with a number of changes made to this, we've just got the memory issues down to a much better level. We also found an issue where an uninitialised variable was being deleted - it's a little tricky to know why it was set up as null in the first several loops of the video, but around 8 or 9 loops in we were finding that the variable wasn't being null-initialized and hence it caused a crash.

Having made these changes we've just tested it with a short 5s video played in a loop (stopped/restarted in the 'onPlayStatus' event handler): memory stats are as follows:
- First 100 loops -> 396kb increase in process memory
- Next 100 loops -> 303kb increase
- Next 100 loops -> 266kb increase

Some of this may just be due to fragmentation or other GC issues (and it's likely exacerbated as this is a running a debug build), we can perhaps see what happens over a longer time period.

Please note, you need to call NetStream.dispose() and also NetConnection.close() to ensure some of the objects are cleaned up properly.

I'll get a test DLL uploaded here so that you can check if it helps with your video too.

Regarding the rework, this is something we are planning for later this year, we've got to finish off the latest Android and Linux changes and then can finally get some more focus onto multimedia..

thanks

**Comment by ajwfrost** [comment] 2021-04-12 21:48
@micha01 fyi if you wanted to check this, or to patch your SDK/app with a fixed DLL:
https://transfer.harman.com/message/63cedR9AYgHu88z9tT560S

Download is available until April 26th..

thanks

**Comment by itlancer** [comment] 2021-04-13 08:16
@ajwfrost, I have replaced this DLL and on video playback start AIR app crashes just after `NetStream.Play.Start` event received.
You can use application example from here to reproduce it https://github.com/Gamua/Adobe-Runtime-Support/issues/80

**Comment by ajwfrost** [comment] 2021-04-13 08:34
Thanks @itlancer  - I can't see how that worked then for our test case... the new link for the DLL which should fix this is:
https://transfer.harman.com/message/XY0XpualRmdLT3fHpFdyjd

thanks

**Comment by itlancer** [comment] 2021-04-13 09:09
@ajwfrost, with latest DLL my basic video test in AIR app works but also have memory leak. Memory increases slower than with AIR SDK 33.1.1.444 but anyway about ~+5-10 MB RAM per video loop using code and video sample from here: https://github.com/Gamua/Adobe-Runtime-Support/issues/80

**Comment by ajwfrost** [comment] 2021-04-13 09:22
@itlancer can you please share the code you're using to loop? The sample there doesn't loop at all..

Our code (snippet):
```
		private function startVideo() : void
		{
			_nc = new NetConnection();
			_nc.connect(null);
			_ns = new NetStream(_nc);
			_ns.client = this;
			_ns.addEventListener(NetStatusEvent.NET_STATUS, onNetStatus);
			_sv.attachNetStream(_ns);
			_sv.viewPort = new Rectangle(0, 0, stage.stageWidth, stage.stageHeight);
			_ns.play("video.mp4");
		}
		
		private function stopVideo() : void
		{
			_ns.removeEventListener(NetStatusEvent.NET_STATUS, onNetStatus);
			_ns.dispose();
			_ns = null;
			_nc.close();
			_nc = null;
			_sv.attachNetStream(null);
		}
		
		public function onPlayStatus(obj : Object) : void
		{
			if (obj.code == "NetStream.Play.Complete")
			{
				stopVideo();
				startVideo();
			}
		}
```
Without the dispose/close on the NetStream and NetConnection objects, then yes we'd expect a memory leak..
We had the test case running for over 2 hours without any significant increases in memory showing up from Windows task manager (or from Scout).

**Comment by itlancer** [comment] 2021-04-13 09:44
@ajwfrost, 
For "loop" here I mean "stop" and "start again" video from blank (with disposing/clearing all and recreation objects).
I have test your example - it works fine. After ~20 video "restarts" it about only +1-2 MB RAM for app (by Windows Task Manager cause Scout doesn't show such memory leaks at all). If there some memory leak least yet- it not so critical as it was.
The difference: you using `StageVideo`, I am using `Video` in latest tests. Didn't test it with `VideoTexture` yet.
You can reproduce memory leaks with latest DLL and `Video` using such code example (it do the same like yours but use `Video` instead of `StageVideo`):
```
package  {
	import flash.display.Sprite;
	import flash.events.Event;
	import flash.net.NetConnection;
	import flash.net.NetStream;
	import flash.media.Video;
	import flash.events.NetStatusEvent;
	
	public class AIR33Video extends Sprite {
		private var video:Video = new Video(640, 480);
		private var nc:NetConnection;
		private var ns:NetStream;
		
		public function AIR33Video() {
			addEventListener(Event.ADDED_TO_STAGE, init);
		}
		
		private function init(e:Event):void {
			removeEventListener(Event.ADDED_TO_STAGE, init);
			
			addChild(video);
			
			nc = new NetConnection();
			nc.addEventListener(NetStatusEvent.NET_STATUS, ncHandler);
			nc.connect(null);
		}
		
		private function ncHandler(e:NetStatusEvent):void {
			if (e.info.code == "NetConnection.Connect.Success"){
				ns = new NetStream(nc);
				ns.client = {onMetaData:getMeta, onComplete:onComplete };
				ns.addEventListener(NetStatusEvent.NET_STATUS, nsHandler);
				video.attachNetStream(ns);
				ns.play("video.mp4");
			}
		}
		
		private function nsHandler(e:NetStatusEvent):void {
			trace(e.info.code);
			if (e.info.code == "NetStream.Play.Stop"){
				//Dispose old
				video.attachNetStream(null);
				ns.removeEventListener(NetStatusEvent.NET_STATUS, nsHandler);
				ns.dispose();
				ns = null;
				
				nc.close();
				nc.removeEventListener(NetStatusEvent.NET_STATUS, ncHandler);
				nc = null;
				
				//Create again
				nc = new NetConnection();
				nc.addEventListener(NetStatusEvent.NET_STATUS, ncHandler);
				nc.connect(null);
			}
		}
		
		private function getMeta(mdata:Object):void { }
		private function onComplete(mdata:Object):void { trace("onComplete"); }
		
	}
}
```

**Comment by ajwfrost** [comment] 2021-04-13 10:25
Okay thanks @itlancer  - so I guess this is also linked to why your test case crashed and ours didn't.. there was a buffer being allocated in the decoder which was unnecessary in the StageVideo case, and had been causing a memory leak, so we took it out. To fix the crash, we've put it back in - but this is now causing a leak again in that StageVideo case, and it's also causing a leak in the Video case as well (although primarily we've just found that the non-StageVideo case is allocating a YUV buffer and that wasn't being properly cleaned up: that was on a per-frame basis! so now these are being recycled..). A bit more to do here perhaps but we can look to get this fixed for both Video and StageVideo. And then as you say, look at VideoTexture.....

thanks

**Comment by ajwfrost** [comment] 2021-04-13 10:54
Third attempt - this time, we've checked it both with the Video and the StageVideo classes. Some differences between how each of them use buffers (plus for the Video case, as well as YUV buffers, the video decoder object and all platform-specific resources were just being left open..).
https://transfer.harman.com/message/AtF9TM6Qy6gqCo5htH0c24

thanks

**Comment by itlancer** [comment] 2021-04-13 11:40
@ajwfrost, with latest DLL seems all works fine. Made a quick checks with `Video`, `StageVideo` and `VideoTexture`. After ~20 video "restarts" it about only +1-2 MB RAM for app in all such cases. May be such "overhead" doesn't related to video functionalities by itself but anyway it not so critical to further tests starts.
Could you please make a release of AIR SDK with these fixes so we could make complex tests for Windows 32/64-bit and macOS (with bundled applications) to return video functionalities to our clients?

**Comment by ajwfrost** [comment] 2021-04-13 11:56
Great, thanks @itlancer  - will look to kick off the next release shortly, we have an Android issue that needs to be pulled in too..

**Comment by micha01** [comment] 2021-04-13 17:12
Hi Andrew and itlancer,
eureka, this seems to work! I made several hundred manual starts and restarts with different Full-HD mp4-videos. With Video and StageVideo. 
Great support, Andrew. Thank you very much and itlancer as well for the tests. Hopefully this fix will be included in the next release.
Michael

**Comment by micha01** [comment] 2021-04-16 16:35
Hi Andrew,
fixed DLL is working fine when tested in ANIMATE with AIR SDK 33.1.1.444. But when I try to publish a project as a desktop app packaging stops with the error message („Packager internal error“). Is this expected? Will this be fixed in next AIR SDK version?
Best regards 
Michael

**Comment by ajwfrost** [comment] 2021-04-16 16:52
Hi - sorry, yes it would have been a build that works fine as a runtime DLL, but didn't include the extra AS3 glue that's used for packaging up applications. If we go through a proper build process, the new SDK will throw out the appropriate DLLs in the correct locations.

New SDK should be out late next week, containing these fixes.

thanks

**Comment by micha01** [comment] 2021-04-28 11:23
Hi Andrew, new SDK 33.1.1.476 is working fine when testing in ANIMATE. But same thing as I discribed above happens when I try to publish it as desktop app: Packaging stops ("Packaging failed. Packager internat error.") Is the "extra AS3 glue" not yet included?

**Comment by itlancer** [comment] 2021-04-28 12:38
@ajwfrost
I also have error `Packaging failed. Packager internat error.` when trying to build bundle for **any** AIR application. Tested via Animate and command line with different applications with Windows device.

**Comment by ajwfrost** [comment] 2021-04-28 12:44
@micha01 @itlancer  thanks for the notifications .. not sure what happened here but I just tried with the downloaded SDK and found the same. I am suspecting another code-signing problem, we'll investigate asap....
thanks

**Comment by ajwfrost** [comment] 2021-04-28 16:58
Closing this one as the video vides are in there, but opening #817 to track the problem with the packaging error...

**Closed by ajwfrost** 2021-04-28 16:58 UTC
Labels: Bug, Platform: Windows

**Comment by itlancer** [comment] 2021-04-30 11:33
@ajwfrost 
Please reopen this issue.
AIR SDK 33.1.1.476 for macOS still have memory leaks.
Looks like there is no fixes like for Windows.

**Comment by simon-lucas** [comment] 2022-01-20 11:37
I have this problem. It is using 33.1.1.575. The memory leak is there on MacOS and Windows. I played a number of videos  and ended up with a 10Gb memory footprint. I tested my project on an old Flash CS6 install with SDK 28.x.x and there is no leak. 

Is there any prospect of a solution for this? I'd be happy to wind back to SDK 30 or 31 for the time being, but Adobe have pulled all AIR archives (SDKs and Air Installers) from their site.
