### ISSUE TITLE
URL Request not working on Samsung Galaxy S9 Android ARMv8

### ISSUE THREAD

**Issue by dgurney75** [Gamua/Adobe-Runtime-Support#793] opened 2021-04-16 16:02 UTC
## Problem Description

URL Requests have stopped working completely for ARMv8 for Android after latest updates pushed to device. See attached screenshots for device info. ARMv7 still works fine.

* Which AIR SDK did you use? AIR SDK for MacOS - (33.1.1.444) Full AIR SDK 
* Describe the affected environment: Adobe Animate CC, Mac OSX Catalina, Android ARMv8, Air for Android, Samsung Galaxy S9
* Can you reproduce it yourself, or did you get reports from other users? I've attached the APK files and source files for reference. ARMv7 works fine but not ARMv8.

## Steps to Reproduce

[urlRequest.zip](https://github.com/Gamua/Adobe-Runtime-Support/files/6326411/urlRequest.zip)

Give us a minimal example:

var myUrlRequest: URLRequest = new URLRequest();
myUrlRequest.method = URLRequestMethod.GET;
myUrlRequest.url = "https://www.google.com";

var myUrlLoader: URLLoader = new URLLoader();
configureListeners(myUrlLoader);
myUrlLoader.load(myUrlRequest);

function configureListeners(dispatcher: IEventDispatcher): void {
	dispatcher.addEventListener(Event.COMPLETE, completeHandler);
	dispatcher.addEventListener(Event.OPEN, openHandler);
	dispatcher.addEventListener(ProgressEvent.PROGRESS, progressHandler);
	dispatcher.addEventListener(SecurityErrorEvent.SECURITY_ERROR, securityErrorHandler);
	dispatcher.addEventListener(HTTPStatusEvent.HTTP_STATUS, httpStatusHandler);
	dispatcher.addEventListener(IOErrorEvent.IO_ERROR, ioErrorHandler);
	dispatcher.addEventListener(HTTPStatusEvent.HTTP_RESPONSE_STATUS, onHttpResponse);
}

function completeHandler(event: Event): void {
	trace("completeHandler: " + event);
}

function openHandler(event: Event): void {
	trace("openHandler: " + event);
}

function progressHandler(event: ProgressEvent): void {
	trace("progressHandler loaded:" + event.bytesLoaded + " total: " + event.bytesTotal);
}

function securityErrorHandler(event: SecurityErrorEvent): void {
	trace("securityErrorHandler: " + event);
}

function httpStatusHandler(event: HTTPStatusEvent): void {
	trace("httpStatusHandler: " + event);
}

function ioErrorHandler(event: IOErrorEvent): void {
	trace("ioError Message: " + event.text);
}

function onHttpResponse(event: HTTPStatusEvent): void {
	trace("httpResponseHandler: " + event);
	trace("STATUS: " + event.status);
}

## Known Workarounds

No workaround I know of currently for affected device.

## Screenshots
![AndroidSettings1](https://user-images.githubusercontent.com/8271407/115051165-248c5800-9ea2-11eb-9575-f71d66551e20.jpg)
![AndroidSettings2](https://user-images.githubusercontent.com/8271407/115051180-281fdf00-9ea2-11eb-82e0-61c278f6021c.jpg)

**Comment by ajwfrost** [comment] 2021-04-16 16:11
Thanks - this is a duplicate of #758 - will update that thread with the latest status..

**Closed by ajwfrost** 2021-04-16 16:11 UTC
