### ISSUE TITLE
Extreme Increase of crashes in Google Play Console

### ISSUE THREAD

**Issue by Marcophono2** [Gamua/Adobe-Runtime-Support#540] opened 2020-11-25 18:43 UTC
Hello!

I have a big problem with my last Android app update. The crash rate increased from 1% to 20%. The only bigger internal technical updates were the webView ANE and the push notification ANE. After a longer discussion with Michael from distriqt I think that I can exclude the ANE updates as the reason for this.  
It started on 11 Oct when I uploaded the first time the 32bit apk version which was exported with targetSDK 29 (before 26). The 64 version was also before available as targetSDK 29 exported and without that crash rate.
On the other hand side there are the 64bit smartphones affected in the Google console, not the 32bit ones. Another thing I did for the first time on 11. Oct was to upload both versions first (64 bis and 32 bit with a higher version number for the 64 bit version) before publishing them together. But I couldn't really imagine that the issue is located there. I have no idea at the moment where I can go on with my research. And idea is welcome!
[ AIR SDK 33.1.1.259 ]

pid: 0, tid: 0 >>> air.marc.waesche.org.marcophono <<<

```
backtrace:
  #00  pc 0000000000083134  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160)
  #00  pc 00000000000a1ce4  /data/app/air.marc.waesche.org.marcophono-St7S7yHhGTIrheCCaFXKDw==/lib/arm64/libc++_shared.so
  #00  pc 00000000000ca13c  /data/app/air.marc.waesche.org.marcophono-St7S7yHhGTIrheCCaFXKDw==/lib/arm64/libc++_shared.so (__cxa_pure_virtual+16)
  #00  pc 000000000025fb04  /data/app/air.marc.waesche.org.marcophono-St7S7yHhGTIrheCCaFXKDw==/lib/arm64/libCore.so
  #00  pc 00000000002dd3b8  /data/app/air.marc.waesche.org.marcophono-St7S7yHhGTIrheCCaFXKDw==/lib/arm64/libCore.so
  #00  pc 0000000000312848  /data/app/air.marc.waesche.org.marcophono-St7S7yHhGTIrheCCaFXKDw==/lib/arm64/libCore.so
  #00  pc 0000000000312130  /data/app/air.marc.waesche.org.marcophono-St7S7yHhGTIrheCCaFXKDw==/lib/arm64/libCore.so
  #00  pc 0000000000312ab4  /data/app/air.marc.waesche.org.marcophono-St7S7yHhGTIrheCCaFXKDw==/lib/arm64/libCore.so
  #00  pc 00000000000e28c0  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36)
  #00  pc 000000000008503c  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
```

Best regards
Marc

![1](https://user-images.githubusercontent.com/22599855/100269091-4c603b00-2f56-11eb-88e8-6472e3838c23.png)
![2](https://user-images.githubusercontent.com/22599855/100269102-4ec29500-2f56-11eb-878a-e0c26698ca20.png)
![3](https://user-images.githubusercontent.com/22599855/100269109-5124ef00-2f56-11eb-9cb1-4e2b0cca6610.png)
![4](https://user-images.githubusercontent.com/22599855/100269117-52eeb280-2f56-11eb-812d-406f36ccebba.png)

**Comment by spielepalast** [comment] 2020-11-26 12:00
Hi Marc,

I can't actually help with the issue you are seeing, but we also have all our apps updated with Air 33.1.1.259 and we do not see an increase of crashes, everything looks very stable. Which version of Air SDK were you using before this update? Can you make another release with the previous version of Air to see if the crash rate drops?

**Comment by ajwfrost** [comment] 2020-11-26 12:21
Okay so this is audio-related again .. apologies, I had assumed you had moved to the .300 build and were seeing the problem we have with the JIT for 64-bit ARM but if this is .259 then it's related to the changes we put in to fix RTMP/audio..

The crash is happening when we are trying to lock a critical section.. in a callback from the Android system, from what we can see, and the callbacks should have stopped when the audio was closed.

With the crash rate around 20%, I would also suggest this is something we have a good chance to test and reproduce here, so if you could send us a package built with apk-debug, we can try to see this happen and then start adding some traces in to see why the callbacks are still coming in if the object holding the Crtical Section has been destroyed.

thanks

**Comment by Marcophono2** [comment] 2020-11-26 13:50
Wonderful, thank you very much, @ajwfrost ! Is there kind of a standard upload interface? I thought you generate and post each time an individual link for uploading!?

Best regards
Marc

**Comment by Marcophono2** [comment] 2020-11-27 18:59
@ajwfrost : Can you send me an upload link, please?

Best regards
Marc

**Comment by ajwfrost** [comment] 2020-11-28 06:21
@Marcophono2  sorry for the delay .. we really should set up some sort of portal for this kind of thing! but in the meantime:
https://transfer.harman.com/requests/tPh5yiByL9FHYODMkzYdVJ
Thanks

**Comment by Marcophono2** [comment] 2020-11-28 10:14
Thank you, @ajwfrost , I have uploaded it.

Best regards
Marc

**Comment by ajwfrost** [comment] 2020-11-28 13:30
Thanks - yes reproduced it here. Interesting error just before the stack dump:
```
11-28 12:58:03.748 10488 27692 27692 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
11-28 12:58:03.748 10488 27692 27692 F DEBUG   : Abort message: 'Pure virtual function called!'
```
We'll take a look..

**Comment by Marcophono2** [comment] 2020-11-28 15:49
I am really happy that you were able to reproduce that issue! Indeed, interesting error message!

**Comment by ajwfrost** [comment] 2020-11-29 07:20
In case you're also able to reproduce this using that build - if you use the below patch version and rebuild it, I think this solves it (just for ARMv8 currently). It wasn't actually a pure virtual call, it was just a thread race and sometimes one thread deleted an object before the Android audio callback had used it (we'd requested the callbacks to stop, but it looks like the callback procedure may have been already started before the request was actioned).
https://eu-transfer.harman.com/message/kksu9lcJGySbOdSvQLxxTL

**Comment by Marcophono2** [comment] 2020-11-29 10:44
@ajwfrost , you are my favorite hero at the moment!! I never realized such a quick, professional and effective support! I am absolutely happy! No, I never could reproduce that issue on one of my test devices but I have uploaded a new apk update to Google Play. Tomorrow I will get the next crash report I think and I will give an update here.
Sure, you have your team in the background. So my thanks of course also to all involved "Harmen"!
Andrew, did the app crashed on your device when that abort message was triggered? And which tool were you using for displaing the debug messages?

Best regards
Marc

**Comment by ajwfrost** [comment] 2020-11-29 12:52
@Marcophono2 That’s just the 64-bit ARM library though, so you’d best get a proper rebuild with our next production release which should be in about 2 weeks (though if you’re not able to use an older SDK until then, I can look at doing a quick-fix on ARMv7 too..?)
Yes we could reproduce it relatively easily on a Samsung S8 with exactly the same call stack and logcat output per your information. Just using logcat and debug reports sent from the Developer menu in Android Settings.. and then we can deploy a special AIR app on this that your app will then use rather than its own C++ library, so that we can get your app to use our debug version. Only when you build with apk-debug though! 
Thanks

**Comment by Marcophono2** [comment] 2020-11-29 12:59
@ajwfrost: I cannot use an older SDK due to the new targetSDK 29 minimum. The last (for me) working SDK was from the targetSDK 28 builts. If the ARMv7 fix is really no effort for you... then yes. :) Sure, the v8 fix was much more important, so it would not bring sleepless nights for me if you can't find the time for the v7 fix.

**Comment by ajwfrost** [comment] 2020-11-29 23:18
Here you go:
https://transfer.harman.com/message/tKjtVUUugJ70LKOssGhOCo

thanks

**Comment by Marcophono2** [comment] 2020-11-30 17:28
Thank you (again), @ajwfrost ! 
The fix (64bit) is working great as you can see at the screenshot! The fixed app version is available since yesterday afternoon. The crash rate decreased enourmously since then. For sure nearly all still registered crashes remain from the not yet updated apps.
![github](https://user-images.githubusercontent.com/22599855/100642806-8c019b00-3339-11eb-9508-c24101b54642.png)

Best regards
Marc

**Comment by Marcophono2** [comment] 2020-11-30 17:57
@ajwfrost Andrew, are you sure that the 32 bit fix must be put into runtimes/air/android/device/Runtime.apk ?
I cannot compile then. In debug mode I get this error message:
`adb: failed to install C:\FlashBuilder\Adobe Flash Builder 4.7 (64 Bit)\eclipse\plugins\com.adobe.flash.compiler_4.7.0.349722\AIRSDK\runtimes\air\android\device\Runtime.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Package /data/app/vmdl1651413566.tmp/base.apk has no certificates at entry AndroidManifest.xml`
I think you mean the folder runtimes/air/android/device/x86, right?

Best regards
Marc

**Comment by Marcophono2** [comment] 2020-12-01 00:09
@spielepalast : Sorry that I didn't come back to you. You were pointing to the right things and as you can read in the following posts (after your post) the reason was rather special and had to do with audio/rtmfp streaming. If I imagine this would have happened in the Adobe "maintaining" time then Good Night! 😱 
I'm from Germany too by the way. 😃

**Comment by Marcophono2** [comment] 2020-12-02 16:59
@ajwfrost : Sorry for bothering again. I wrote that I can live without the 32bit fix for the next two weeks due to rather few affected users of about 6%. But I realized now that this small group will bring the average crash rate of all users above the limit to "bad behaviour". 
20% crash rate x 6% of all users = 1.2%. So even if the 64bit users have a crash rate of 0% it would be a bit too much. So, if you have an quick&dirty fix for the 32bit fix which is not working here, I would be happy. Otherwise waiting for the next AIR SDK is also okay. I cannot beleave that being a little bit above that "bad behaviour" limit will start a full Google Play store listing punch. 

Best regards
Marc

P.S.: What I wrote in the last post was obviously not correct. x86 is the intel chip based platform.
I am working on Flash Builder for Windows. May be that is the reason that you can compile with the 32bit fix (command line I could imagine)  and I can not.

**Comment by GeneralVimes** [comment] 2020-12-04 09:35
Good thread!
I noticed the same increase in crashes, but in my case, trace logs contain even less info
![image](https://user-images.githubusercontent.com/7909250/101147005-75529100-3624-11eb-8523-f56f481d53d2.png)

My game was built with the previous AIR version, 33.1.1.259. The crash rate was well below the bad behavior threshold.
On Nov 21st I released the version 1.1.4, which had balance fixes and which I built with a fresh AIR 33.1.1.300.

Crash rate has immediately started growing. So, on the 22nd Nov I released the update 1.1.4.1 which was the same as 1.1.4, but built with 33.1.1.259 (which I luckily stored in a backup). Crash rate was reduced, and then on Nov 29th I also used 33.1.1.259 to build the game version 1.1.5

Here’s more detailed data about the release 1.1.4:
![image](https://user-images.githubusercontent.com/7909250/101147036-81d6e980-3624-11eb-9b8d-fdbc88f321dc.png)

Interesting that only the 64-bit version was above the bad threshold:

![image](https://user-images.githubusercontent.com/7909250/101147077-90bd9c00-3624-11eb-8d66-883eed3a1c9c.png)

And the affected Android versions were Android 9 and 10:
![image](https://user-images.githubusercontent.com/7909250/101147115-9b783100-3624-11eb-8d92-906fa94d53e5.png)

For comparison, this is how 1.1.4.1 looks like (which is the same as 1.1.4 but built with 33.1.1.259):
![image](https://user-images.githubusercontent.com/7909250/101147133-a16e1200-3624-11eb-8d5f-068ca584e36a.png)

If I look at the crashes details in 1.1.4, the console does not give much info. Like, when the crash is caused by some SDK, we can see the stack trace with this SDK.

![image](https://user-images.githubusercontent.com/7909250/101147153-a92db680-3624-11eb-9c07-ae56a3205dd8.png)

And the detailed info about the biggest crash:

![image](https://user-images.githubusercontent.com/7909250/101147166-ae8b0100-3624-11eb-9c72-01d67d70160e.png)

![image](https://user-images.githubusercontent.com/7909250/101147189-b77bd280-3624-11eb-91fb-f5b54e72d20a.png)

This is all what console shows

**Comment by ajwfrost** [comment] 2020-12-04 16:20
@GeneralVimes thanks, yes that looks like the issue we have with the JIT in the 64-bit ARM code. Will be fixed in the forth coming release (and in the patch from above: https://transfer.harman.com/message/tKjtVUUugJ70LKOssGhOCo which needs to go into the runtimes\air\android\device\arm8 folder of the SDK..)

@Marcophono2 not sure what went wrong with the 32-bit ARM binary there, that was the right path. Ah .. although, it looks like you were then using ADB to try to push that to Android: the runtime APK file is just used as an archive/template for us when the ADT tool is creating the output package. So, if you put that Runtime.apk file into the parent folder (there are subfolders for the other architectures, but ARMv7 sits just in the 'device' folder) and then use the ADT (or your IDE) to create your APK package for 32-bit ARM, it should then work..

**Comment by Marcophono2** [comment] 2020-12-04 17:08
@ajwfrost 
You wrote `"So, if you put that Runtime.apk file into the parent folder (there are subfolders for the other architectures, but ARMv7 sits just in the 'device' folder) and then use the ADT (or your IDE) to create your APK package for 32-bit ARM, it should then work.."`

That was what I tried. ;)

**Comment by leossmith** [comment] 2020-12-08 09:41
And our app has officially being tagged for bad behavior and downloads and revenues dropped due to crashes.

Can we get a copy of .259 to revert back to the previous version?

**Comment by ajwfrost** [comment] 2020-12-08 09:43
Of course: https://airsdk.harman.com/download/33.1.1.259

**Comment by ajwfrost** [comment] 2020-12-08 09:45
@Marcophono2  just saw your comment above ... the error that you had pasted earlier was:

> adb: failed to install C:\FlashBuilder\Adobe Flash Builder 4.7 (64 Bit)\eclipse\plugins\com.adobe.flash.compiler_4.7.0.349722\AIRSDK\runtimes\air\android\device\Runtime.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Package /data/app/vmdl1651413566.tmp/base.apk has no certificates at entry AndroidManifest.xml

which implies you're trying to use ADB to install that Runtime.apk file. So if you're just building your application using ADT normally, what is the error you get?

thanks

**Comment by leossmith** [comment] 2020-12-08 09:50
Thanks @ajwfrost . When should we expect a fix for this?

![image](https://user-images.githubusercontent.com/4300876/101467829-87497200-394b-11eb-9f6f-4eadaa3ee17a.png)


![image](https://user-images.githubusercontent.com/4300876/101467776-713bb180-394b-11eb-98c0-02a5e93a137e.png)

**Comment by ajwfrost** [comment] 2020-12-08 12:10
I'd been hoping to get a couple of other ongoing pieces into the next release but can't really delay it further .. so we'll kick off the process today and the release should be available Monday or Tuesday next week..

thanks

**Comment by Marcophono2** [comment] 2020-12-09 19:07
> @Marcophono2 just saw your comment above ... the error that you had pasted earlier was:
> which implies you're trying to use ADB to install that Runtime.apk file. So if you're just building your application using ADT normally, what is the error you get?

@ajwfrost Strange. Now it worked like a charme! I did not try this time to install the app in debug mode. Producing the product apk + installing it on the attached device worked wonderful. Also this way resulted in an error 2 weeks ago. May be there was anything left in the cache or whatever. I have uploaded not the fixed 32bit version (together with an updated 64bit version number).

Thank you very much, Andrew!

**Comment by Marcophono2** [comment] 2020-12-09 19:17
@ajwfrost Just to add: The crash rate for the fixed 64bit version is/was 0.54%. This is much better than the 1.05 - 1.1% I had in the last years. 👍

**Comment by Marcophono2** [comment] 2020-12-15 19:49
Proudly reporting that my crash rate is low as is has never been before. Since also having uploaded the app with the fix for the 32bit version the crash rate is now around 0.4%. Thank you, Andrew! I will close this issue now.

Best
Marc

![AIR](https://user-images.githubusercontent.com/22599855/102264883-8ea5e800-3f16-11eb-8b3b-b324db663925.png)

**Closed** 2020-12-15 19:49 UTC

**Comment by berkayk** [comment] 2020-12-16 08:00
@Marcophono2 Are you using 259 for this low crash rate? Or did you do another thing?

**Comment by Marcophono2** [comment] 2020-12-16 12:34
@berkayk : I am using 33.1.1.300. BUT with the fix Andrew published here. Two fixes to be more correct. One for the 64bit version and one for the 32bit version. It seems that the links for downloading the fixes do not work any more. I can send you the fixes if you want.

Best regards
Marc

**Comment by berkayk** [comment] 2020-12-16 15:04
@Marcophono2 Link would be great! Thanks.

**Comment by Marcophono2** [comment] 2020-12-16 15:27
@berkayk Can you send me an email to marc@waesche.org ?

**Comment by Marcophono2** [comment] 2020-12-16 15:27
@berkayk I forgot to ask: Are you using Flash Builder?
