### ISSUE TITLE
Harman SDK 33.1.1.86 I'm stuck on splash screen when I try to debug on android

### ISSUE THREAD

**Issue by tudal** [Gamua/Adobe-Runtime-Support#285] opened 2020-03-31 11:59 UTC
## Problem Description

App is starting. All trace looks normal, theres even game sounds. Just like this Harman splashscreen is covering everything and someone forgot about removeChild.
On two android phones.
It occurs only when I try debug app by Intellij (14.1.7) with USB cable. Without debugging splashscreen dissapears correctly.
It occurs even when I compile empty project with just one trace.
Tried 32 and 64

## Steps to Reproduce

Start debugging AIR app in Intellij on android phone

## Known Workarounds

none

**Comment by marchbold** [comment] 2020-03-31 12:02
Same situation here. 

Adding a license to remove the splash has the application is working normally.

**Comment by fedor-strelkov** [comment] 2020-04-01 17:22
In my case the splash screen always gets stuck covering the app and it never goes away.
I tested on Android 5.1. If I use 'landscape' for aspectRatio then the splash screen is distorted and it doesn't fit on the screen (see attached screenshot).
SDK 33.1.1.86 is the first one from Harman I tried. The issue is very confusing to me.
![Screenshot_2020-04-01-18-42-29-sdk_33 1 1 86](https://user-images.githubusercontent.com/62955512/78167053-79575f00-7456-11ea-918d-5bd3c8dc6169.png)

**Comment by ajwfrost** [comment] 2020-04-01 18:32
Hi guys

Apologies for this - we’re already addressing the distortion of the image, and will also check why there’s a problem dismissing the splash screen if you’re debugging. We’re hoping to do an update in the fairly short term to get these problems put to bed!

Thanks

**Comment by ajwfrost** [comment] 2020-04-02 13:07
Quick update here - we can see this happening if you pause the start-up by having a breakpoint in the main class constructor. Not sure whether adding a 'trace' will be doing a similar sort of thing here if you're using IntelliJ IDEA.. we're using Flash Builder for this (where, with a 'trace' but no breakpoint, it works fine).

So assuming this is the same thing, we should be able to get a fix for this. I might get a test file uploaded here so that you can check it though..!

**Comment by ajwfrost** [comment] 2020-04-02 17:26
Hi - are you able to see whether the below file helps with both of these issues? Needs to be copied into the SDK's "lib/android/lib" folder:

https://transfer.harman.com/messages/e291XCX4GK2KpEvPXFSRxG/attachments/PnIMtsTv26Yr7MElOUuGES/download/runtimeClasses.jar
(450 KB) Checksum (SHA256): bb2c61df6da73dd631cd5d7e8caaf2cdda5109b4815f13d6df1b439d7987c586

**Comment by fedor-strelkov** [comment] 2020-04-02 17:48
Replaced runtimeClasses.jar => no Harman splash screen at all.
I tested on Android 5.1, landscape, both apk-captive-runtime and apk-debug.

**Comment by ajwfrost** [comment] 2020-04-02 17:51
If you’re debugging then it looks like the timings work out such that we take down the splash screen before it’s actually displayed :-)

**Comment by fedor-strelkov** [comment] 2020-04-02 17:58
With your updated jar I did not see the splash screen even without debugging.
With the originally deployed SDK 33.1.1.86 the splash screen is always displayed for me, either in debug or in release mode, making the app totally unusable. Actually I've already solved this issue - I've purchased a license from Harman :) A weird solution though...

**Comment by ajwfrost** [comment] 2020-04-02 18:12
Okay that's odd! and when I just try it here, I'm just getting a black screen. Something went wrong there..! Will get this investigated again...

**Comment by tudal** [comment] 2020-04-14 08:46
Ok. All good in 33.1.1.98 :)

**Comment by ajwfrost** [comment] 2020-04-28 07:11
Thanks for confirming, closing this one now..

**Closed by ajwfrost** 2020-04-28 07:11 UTC
Labels: Bug, Platform: Android, Runtime: AIR
