### ISSUE TITLE
Black Screen Start Up Delay

### ISSUE THREAD

**Issue by dmunsie** [Gamua/Adobe-Runtime-Support#411] opened 2020-07-30 15:16 UTC
At app load the splash logo is shown right away (which is great!) but then the logo disappears and a black screen is shown. About 6 seconds later the app starts running. The actual length of the black screen delay seems to vary a bit by device.

Is there anything we can do to limit the length of this delay? Thank you.

**Comment by ajwfrost** [comment] 2020-07-31 10:22
Hi

This is a duplicate of the "black flicker" type issue but perhaps is a little more than a flicker for you! The problem appears to be caused by the removal of the launch storyboard prior to us being ready to display the first AIR-based screen. We're looking to see if there is a way for us to mitigate this, by immediately moving to another storyboard showing the same thing whilst we load in and initialise the SWF code in the background.

If you wanted it to be more of a flicker than a long wait, then you may need to refactor your app to use an initial class that displays a simple bitmap/graphic to give the user something to look at, whilst then it launches the existing class and presumably this is then loading assets, passing things up to the GPU, etc..

thanks

**Closed** 2020-08-07 15:59 UTC
