### ISSUE TITLE
AIR 33.1.1.98 crash on startup on any Android below 4.2 (below API level 17)

### ISSUE THREAD

**Issue by bontegames** [Gamua/Adobe-Runtime-Support#366] opened 2020-06-30 08:03 UTC
Since I updated to the latest AIR version (33.1.1.98) I'm getting lots of crash reports from older phones. upon closer examination I discovered that the crash happens at startup on any Android device below version 4.2, so below API level 17, every time.
This is really worrying since my apps with previous AIR versions work on older devices.

```
FATAL EXCEPTION: main
java.lang.UnsatisfiedLinkError: Native method not found: com.adobe.air.AIRWindowSurfaceView.nativeSurfaceCreated:()V
	at com.adobe.air.AIRWindowSurfaceView.nativeSurfaceCreated(Native Method)
	at com.adobe.air.AIRWindowSurfaceView.surfaceCreated(AIRWindowSurfaceView.java:730)
	at android.view.SurfaceView.updateWindow(SurfaceView.java:609)
	at android.view.SurfaceView.access$000(SurfaceView.java:86)
	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:178)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:703)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1956)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1120)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4604)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
	at android.view.Choreographer.doCallbacks(Choreographer.java:555)
	at android.view.Choreographer.doFrame(Choreographer.java:525)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
	at android.os.Handler.handleCallback(Handler.java:615)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4921)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
```

**Comment by marchbold** [comment] 2020-06-30 08:31
Is it worrying? You are talking about < 2% of devices at 4.3 (API 18) and below. 

We generally do minimum of 19 for our apps now (4.4 kitkat) and I would actually encourage AIR to increase the minimum to that as well. 

Have you added the multidex name to your application tag in your manifest additions? 


```xml
<manifest android:installLocation="auto">
	<!-- PERMISSIONS -->

	<application android:name="androidx.multidex.MultiDexApplication">

		<!-- ACTIVITIES / RECEIVERS / SERVICES -->

	</application>
</manifest>
```

Or if you aren't using AndroidX and the `androidx.multidex` extension, replace the name to be `android.support.multidex.MultiDexApplication`

**Comment by ajwfrost** [comment] 2020-06-30 08:37
Hi

We actually know what the issue is here - we had to do an update of one of the libraries that's linked with AIR in order to fix an audio issue (echo cancellation module I think), and although this was built on an old Android source environment, it wasn't old enough and it ended up with an incompatibility for pre-KitKat devices.

Our action here is to set up a very old Android environment and build the module for that .. which isn't easy, the developer reported all sorts of issues in setting up the Android build environment and getting hold some of the required software. So it's still on our things to do but not the highest priority right now due to the smaller number of devices: currently we have e.g. problems when setting the target SDK to 29 that we are focusing on..

thanks

**Comment by ajwfrost** [comment] 2020-06-30 08:39
FYI this is a duplicate of #278

**Comment by zwetan** [comment] 2020-06-30 23:45
> Is it worrying? You are talking about < 2% of devices at 4.3 (API 18) and below.
> 
> We generally do minimum of 19 for our apps now (4.4 kitkat) and I would actually encourage AIR to increase the minimum to that as well.

100% agreeing on this

also someone really willing to support those < 2% could produce an Android APK 32-bit with AIR 32
and produce an APK 64-bit with 33.1.1.98+

**Comment by bontegames** [comment] 2020-07-01 08:01
Thanks for the reply, I agree that this is only affecting a small number of devices and no priority.
Unfortunately it's the small percentage of users that were leaving 1 star ratings because of the crash.
Maybe a mention in the release notes that AIR is no longer (or for the moment) supporting API levels lower than 17 can avoid this for other devs?

**Comment by zwetan** [comment] 2020-07-01 10:24
> Maybe a mention in the release notes that AIR is no longer (or for the moment) supporting API levels lower than 17 can avoid this for other devs?

see my suggestion above, it should prevent those crashes

you can publish multiple APK targeting device screen size, language, etc.
take advantage of this to target those particular 2%

**Comment by bontegames** [comment] 2020-07-01 10:47
> also someone really willing to support those < 2% could produce an Android APK 32-bit with AIR 32
and produce an APK 64-bit with 33.1.1.98+

AIR 32 has a bug that makes this not an option for me (AIR-181: Android ‘back’ button cannot be handled in ActionScript (Gamua #73 )).
So my solution is now to set minimum target version at 17. 


> Maybe a mention in the release notes that AIR is no longer (or for the moment) supporting API levels lower than 17 can avoid this for other devs?

This suggestion just to prevent other developers from targeting to low and not knowing why they get crashes on certain devices (since this was not a problem before).

**Comment by zwetan** [comment] 2020-07-01 10:59
> AIR 32 has a bug that makes this not an option for me

there is an ANE solution

anyway, I think you starts to see that supporting those 2% require a lot more efforts and may I say probably not worth it

> So my solution is now to set minimum target version at 17.

perfectly acceptable and I would say normal

**Comment by marchbold** [comment] 2020-07-05 07:57
Closing duplicate: #278

**Closed by marchbold** 2020-07-05 07:57 UTC
