### ISSUE TITLE
Unable to build since .444 (M1 Macs only)

### ISSUE THREAD

**Issue by ventr1x** [Gamua/Adobe-Runtime-Support#799] opened 2021-04-19 18:38 UTC
One of our devs currently has a M1 Mac Mini and is unable to build any apps for iOS since .444

Error Message:

```
Warning: Using default implementation for native extension 'com.google.android.material'<br>
Warning: Using default implementation for native extension 'com.distriqt.CustomResources'<br>
Exception in thread "main" <br>java.lang.NoSuchMethodError: 'sun.security.util.ObjectIdentifier sun.security.util.ObjectIdentifier.newInternal(int[])'<br>	
	at com.adobe.air.ipa.MachoSigner.signToStream(MachoSigner.java)<br>	
	at com.adobe.air.ipa.MachoSigner.newCMSBlob(MachoSigner.java)<br>	
	at com.adobe.air.ipa.MachoSigner.sign(MachoSigner.java)<br>	
	at com.adobe.air.ipa.MachoSigner.sign(MachoSigner.java)<br>	
	at com.adobe.air.ipa.IPASigner.signMacho(IPASigner.java)<br>	
	at com.adobe.air.ipa.IPAOutputStream.finalizeFrameworkSig(IPAOutputStream.java)<br>	
	at com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)<br>	
	at com.adobe.air.ipa.IPAPackager.createPackage(IPAPackager.java)<br>	
	at com.adobe.air.ADT.parseArgsAndGo(ADT.java)<br>	
	at com.adobe.air.ADT.run(ADT.java)<br>	
	at com.adobe.air.ADT.main(ADT.java)
```

Mac details
![m1_info](https://user-images.githubusercontent.com/7974355/115285784-938dd900-a14e-11eb-8b31-de716b87bf9d.png)

I have no issue with a MBPro 2018.

Without me poking much into it, it feels like a java sdk issue. If that might be the case I can post the used version tomorrow. As there is no official Sun/Oracle Java build we're using a version from adoptopenjdk

**Comment by ajwfrost** [comment] 2021-04-19 18:42
Hi

Yes this is a JVM issue, the signing uses internal Sun/Oracle classes from their JVM. It looks like we may need to look at using a different mechanism if people aren't going to have this one installed (although I'm 99% sure I use OpenJDK and it works okay..)

Might be worth checking if you're using an IDE to see in case they're using a different JVM though? We had this issue reported before and the developer had to update some IntelliJ settings I think, before they got it working.

thanks

**Comment by ventr1x** [comment] 2021-04-19 18:47
I'll go through it with the developer tomorrow. 
We're using intellij, maybe it's using some bundled weird jvm.

**Comment by ajwfrost** [comment] 2021-04-20 05:42
Thanks yes - interestingly though, these classes do all seem to be found within OpenJDK which will be why mine is working! and hopefully means that people can switch to using this one if they're not happy with the Oracle Ts&Cs.
e.g. https://code.yawk.at/java/7/sun/security/util/ObjectIdentifier.java

thanks

**Comment by ventr1x** [comment] 2021-04-20 07:37
Java infos:

openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment Zulu15.29+15-CA (build 15.0.2+7)
OpenJDK 64-Bit Server VM Zulu15.29+15-CA (build 15.0.2+7, mixed mode, sharing)

Which is adopt OpenJDK 11

**Comment by ajwfrost** [comment] 2021-04-20 08:29
If using OpenJDK it should be okay even version 15 (and 11) e.g.
https://code.yawk.at/java/15/java.base/sun/security/util/ObjectIdentifier.java
Not sure about Zulu..
One other thing though, it may be that you need the JDK version rather than the JRE version?

**Comment by ventr1x** [comment] 2021-04-20 08:32
They are JDK versions

![8e38-8bff-2f05-67c8](https://user-images.githubusercontent.com/7974355/115364407-a8f11a80-a1c3-11eb-88b6-9eb824bb5f8d.png)

**Comment by ajwfrost** [comment] 2021-04-20 08:53
With AdoptOpenJDK builds it looks like you could end up with an Eclipse OpenJ9 VM which may be the issue here..?
Ultimately of course, the problem is that ADT uses 'private' classes i.e. sun.security.xxx which aren't part of the official Java API set so it's not portable/future-proof. We should look at removing that dependency, although it won't be a quick job to do that! (except, for Mac we could just call `codesign` directly which will resolve all sorts of problems...)

Since this is a Mac-specific issue currently, we could actually have a go at updating this to see if it helps - we can try to get a trial version of ADT out later in the week to work around this... 

thanks

**Comment by ventr1x** [comment] 2021-04-20 09:37
Completely removing the zulu version fixed this.
So, openjdk does work

openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

**Comment by ajwfrost** [comment] 2021-04-20 10:59
Interesting! thanks for confirming. Must have been some sort of conflict/priority issue I guess.
Closing this one then ..

thanks

**Closed by ajwfrost** 2021-04-20 10:59 UTC

**Comment by Dima107** [comment] 2021-05-05 09:20
Hi
I have same problem
How to fix this?
Which exactly OpenJDK will help to fix this

**Comment by ajwfrost** [comment] 2021-05-05 09:57
OpenJDK seems to work - we've now tried a number of these, I think 8, 9, 11, 12, 15...
The above issue was that another JVM was conflicting somehow.. There are different ways to identify how to call "java" - either via the path, or via the JAVA_HOME variable - so I would guess that the system is ending up with a bit of confusion and calls the wrong one.

Do you have any other JRE available? what do you get from a terminal window if you run
```
which java
echo $JAVA_HOME
```
?

thanks
