### ISSUE TITLE
AIR 33.1.1.63 com.mesmotronic.ane::AndroidFullScreen is not defined.

### ISSUE THREAD

**Issue by orcuncun** [Gamua/Adobe-Runtime-Support#276] opened 2020-03-24 13:35 UTC
Error #1065: Variable com.mesmotronic.ane::AndroidFullScreen is not defined.

**Comment by ajwfrost** [comment] 2020-03-24 13:42
Another duplicate of #259 ..

**Closed** 2020-03-25 10:22 UTC
