### ISSUE TITLE
[Android] Back button key down event targetsdk v28 

### ISSUE THREAD

**Issue by marchbold** [Gamua/Adobe-Runtime-Support#73] opened 2019-08-06 09:04 UTC
## Problem Description

The `KeyboardEvent.KEY_DOWN` event fails to get dispatched when pressing the back button on Android and targeting SDK v28. 

This occurs with 32.0.0.116 (Adobe) and  33.0.0.212 (Harman)

## Steps to Reproduce

With target 27 the following will catch the back button and prevent the app from minimising:

```as3
NativeApplication.nativeApplication.addEventListener( KeyboardEvent.KEY_DOWN, keyDownHandler );

function keyDownHandler( event:KeyboardEvent ):void
{
	trace( event.keyCode );
	if (event.keyCode == Keyboard.BACK)
	{
		event.preventDefault();
	}
}
```
(Same occurs with the `stage`).

When we change to target sdk 28 this event is not triggered. I.e. the following is added to the manifest additions:

```xml
<uses-sdk android:minSdkVersion="19" android:targetSdkVersion="28" />
```

## Known Workarounds

Reduce targetSdkVersion to 27.

**Comment by ajwfrost** [comment] 2019-08-06 21:41
Thanks to further input from @marchbold we should have the root cause of this problem and are intending to fix that in this week's SDK release...

**Comment by marchbold** [comment] 2019-08-07 00:11
@ajwfrost Cheers Andrew! 

We also have an ANE resolution for anyone needing an immediate fix for AIR 32.

**Comment by ajwfrost** [comment] 2019-08-16 14:40
Fixed in AIR 33.0.1.220 (or via ANE for previous versions, see updates above)

**Closed by ajwfrost** 2019-08-16 14:40 UTC

**Comment by shajby1** [comment] 2019-09-08 17:56
Is this fixed in 33.0.2.246 & API Level 28? It doesn't work for me, the app is minimized once I press a BACK button on my device. Thanks!

**Comment by rodrigocollavo** [comment] 2019-10-03 15:50
@ajwfrost can you provide any info to understand what has changes on android API 28 that is affecting previous AIR versions? Im trying to find an alternative solution through my custom ANE because I can't update to 33 yet, but I didn't find any bug report like this for native application, I appreciate any info you can provide about how it was fixed or what's the main reason that games were affected by this API 28 in particular. thanks

**Comment by ajwfrost** [comment] 2019-10-11 09:00
Hi

@shajby1  - can you please confirm the device you were using for this? and presumably you were using the simple test case from the bug report?

@rodrigocollavo - there's a link below to the same issue reported on StackOverflow for a normal app.  This can be solved by calling requestFocus() on the main view.
https://stackoverflow.com/questions/52074298/requestfocus-for-edittext-not-working-on-devices-running-android-p-api-28

thanks

**Comment by shajby1** [comment] 2019-10-11 09:07
@ajwfrost Hi there, it's working fine now. Until now I have been using (It worked ok with AIR 32 but didn't work with AIR 33):

```
if(Capabilities.cpuArchitecture=="ARM"){
	NativeApplication.nativeApplication.addEventListener(KeyboardEvent.KEY_DOWN, _onKeyDown);
}
```

When I remove this condition, then it works fine:

`if(Capabilities.cpuArchitecture=="ARM")`

**Comment by ajwfrost** [comment] 2019-10-11 10:27
Ah - okay, so with v33 and 64-bit support, cpuArchitecture is now "ARM64"... that would explain it!
