### ISSUE TITLE
[AIR 33.1.1.50] Crash when GPU memory limit is reached

### ISSUE THREAD

**Issue by Adolio** [Gamua/Adobe-Runtime-Support#245] opened 2020-02-28 15:50 UTC
## Problem Description

The application is crashing when GPU memory limit is reached.

* AIR SDK 33.1.1.50
* Windows 10

### Expected result

An `Error` should be raised as before:

`Error: Error #3691: Resource limit for this resource type exceeded.`

## Steps to Reproduce

The following code can reproduce the issue:

```
package ch.adolio.test
{
	import flash.display.BitmapData;
	import starling.display.Sprite;
	import starling.textures.Texture;
	
	public class OutOfGPUMemoryTest extends Sprite
	{
		public function OutOfGPUMemoryTest()
		{
			var bitmapData:BitmapData = new BitmapData(2048, 2048);

			try
			{
				while (true)
				{
					Texture.fromBitmapData(bitmapData);
				}
			}
			catch (e:Error)
			{
				// GPU memory limit reached
				trace(e);
			}
		}
	}
}
```

## Known Workarounds

N/A

**Comment by ajwfrost** [comment] 2020-02-28 19:33
See release notes: we had been asked by a few folk to remove those limits. So your existing applications shouldn't be impacted, it's only if you have a new application that's got a namespace of 33.1, and then the limits don't apply. So undefined behaviour if you run out of GPU memory..

**Comment by Adolio** [comment] 2020-03-02 09:38
Yep, that's a great feature actually. I really like that move forward!

My concern is more about the fact that if a crash occurs it will make our life way easier if we can know to source of the issue. Plus, it will let the app developer decides what to do (unloading textures, printing a message for the user, detecting incompatible devices, etc.). This will also prevent you to get crash reports with unclear cause...

The low level graphic API doesn't tell you anything about out of memory error?

**Comment by ajwfrost** [comment] 2020-03-02 11:20
This may be dependent upon the underlying implementation; whether Windows is just closing us down or whether there's a null pointer returned from something that we're then not handling. Will ask one of the guys to investigate the exact cause of the crash..

**Comment by itlancer** [comment] 2020-03-02 12:18
Agree with @Adolio.
We need some way to determine "how much GPU memory used" and catch errors to decide what to do by application when using low-level devices etc.
We have `Context3D::totalGPUMemory` property (https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display3D/Context3D.html#totalGPUMemory) but we don't know right now how much video memory "in use" and can't prevent crash anyway.

For me best way too see in future releases:
1) Some `Context3D::usedGPUMemory` property.
2) Catch "out of video memory" errors to prevent crash and handle it via application code.

**Comment by ajwfrost** [comment] 2020-03-03 09:04
@Adolio can I check here what happens if you run this via ADL from a command line? The folk here have found:
a) running from the command line we get an output "error: out of memory" which I believe is the AIR runtime itself deciding to abort due to OOM - so the graphic-specific issue isn't being caught in there.
b) they refactored the app to create the textures in each frame and pushing them into a vector to avoid GC, but then we didn't get the error. Instead, GPU memory seemed to go in a saw-tooth pattern. Although that's probably just overflow of the integer ... We do eventually get to the same "error: out of memory" report.

All of which basically means that it sounds like the GPU is handling things fine (and probably itself falling back to software/general purpose memory when it hits its limits), and the out of memory error is then caused just by the continual allocation of ActionScript objects.

If you're also seeing "error: out of memory" followed by a hang (rather than an actual crash) then we're at least on the same page and we will check what the situation is where this is thrown; if you see something else then could we get your XML/SWF files to see if we can reproduce it?

@itlancer  The `totalGPUMemory` figure should I believe be the amount of memory that we have requested from the GPU i.e. storage for buffers and textures etc. So this is the 'in use' value..

**Comment by itlancer** [comment] 2020-03-03 09:22
@ajwfrost, sorry, my mistake.
Yes, `totalGPUMemory` is "in use" value. But we don't have "total available GPU memory".

**Comment by Adolio** [comment] 2020-03-04 16:14
@ajwfrost Thanks for the investigations! From my side the issue can be closed 🙂 Sorry for the inconvenience.

a) Yes, indeed I confirm that I get a `error: out of memory` when running it from the console with a hang of ADL.
b) Good point! That was the issue. I have updated my test & things are getting really slow over the time but the "crash" doesn't occur anymore (see below).

☝️ Please note that one minor thing I discovered with my new test is that `Context3D::totalGPUMemory ` apparently cycles when reaching 4GB... I'm using ADL 32-bit.

```
[252] 4050.255 MB
[253] 4066.260 MB
[254] 4082.265 MB
[255] 2.270 MB
[256] 18.275 MB
[257] 34.280 MB
```

@itlancer With the latest discoveries, I don't think "total available GPU memory" is still required for that specific issue... It indeed might be very useful for certain situations...

---

For anyone curious of the a better implementation to test GPU memory.

```as3
package ch.adolio.test
{
	import flash.display.BitmapData;
	import starling.animation.IAnimatable;
	import starling.core.Starling;
	import starling.display.Image;
	import starling.display.Sprite;
	import starling.textures.Texture;
	
	public class OutOfGPUMemoryTest extends Sprite implements IAnimatable
	{
		public var _framesCount:uint = 0;
		public var _bitmapData:BitmapData = new BitmapData(2048, 2048);

		public function OutOfGPUMemoryTest()
		{
			Starling.juggler.add(this);
		}

		public function advanceTime(elapsedTime:Number):void
		{
			try
			{
				// create image
				var img:Image = new Image(Texture.fromBitmapData(_bitmapData));
				img.width = img.height = 100;
				img.x = Math.random() * (Starling.current.stage.stageWidth - img.width);
				img.y = Math.random() * (Starling.current.stage.stageHeight - img.height);
				img.color = Math.random() * 0xffffff;
				addChild(img);

				// trace frame & memory usage
				trace("["+_framesCount+"] "+ (Starling.context.totalGPUMemory / 1024 / 1024).toFixed(3) + " MB");
				++_framesCount;
			}
			catch (e:Error)
			{
				// GPU memory limit reached
				trace(e);
			}
		}
	}
}
```

**Comment by zwetan** [comment] 2020-03-05 17:53
@ajwfrost 
for info, there are many parts inside the AVM2 that are limited to 4GB (`UINT32_T_MAX`)
the maximum amount that a ByteArray can contain

so if somewhere in the GPU pipeline ByteArray are used then that could explain the OOM crash

guessing here, it could be anything else

**Closed** 2020-06-30 14:45 UTC
Labels: Platform: Desktop
